# Generated by Django 4.0.2 on 2022-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, unique=True, verbose_name='Customer code')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('active', models.BooleanField(default=True, verbose_name='Is active?')),
            ],
        ),
    ]
