# Generated by Django 4.0.2 on 2022-03-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='Template name')),
                ('company', models.BooleanField(default=False, verbose_name='company')),
                ('date_full', models.BooleanField(default=False, verbose_name='Date (Full)')),
                ('date_be', models.BooleanField(default=False, verbose_name='Date (พ.ศ.)')),
                ('date_ad', models.BooleanField(default=False, verbose_name='Date (ค.ศ.)')),
                ('product_name', models.BooleanField(verbose_name='Product Name')),
                ('flux_no', models.BooleanField(verbose_name='Flux No.')),
                ('lot_no', models.BooleanField(default=False, verbose_name='Lot No.')),
                ('quantity_kg', models.BooleanField(default=False, verbose_name='Quantity (Kg.)')),
                ('quantity_pole', models.BooleanField(default=False, verbose_name='Quantity (แท่ง)')),
                ('quantity_roll', models.BooleanField(verbose_name='Quantity (ม้วน)')),
                ('product_code', models.BooleanField(default=False, verbose_name='Product Code')),
                ('manufacturing_date', models.BooleanField(default=False, verbose_name='Manufacturing Date')),
                ('expiry_date', models.BooleanField(default=False, verbose_name='Expiry Date')),
                ('part_code_project', models.BooleanField(default=False, verbose_name='Part Code Project')),
                ('po_name', models.BooleanField(default=False, verbose_name='P/O')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers', verbose_name='Customer name')),
            ],
        ),
    ]
