# Generated by Django 4.0.2 on 2022-02-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_result_name', models.CharField(max_length=255, verbose_name='Sample Result Name')),
                ('type', models.CharField(max_length=255, verbose_name='Type')),
                ('measure_date_time', models.DateTimeField()),
                ('recalculation_date_time', models.DateTimeField()),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('method_name', models.CharField(max_length=255, verbose_name='Method Name')),
                ('operator_name', models.CharField(max_length=255, verbose_name='Operator Name')),
                ('check_type', models.CharField(max_length=255, verbose_name='Check Type')),
                ('check_status', models.CharField(max_length=255, verbose_name='Check Status')),
                ('grade_verification_name', models.CharField(max_length=255, verbose_name='Grade Verification Name')),
                ('grade_verification_similarity', models.CharField(max_length=255, verbose_name='Grade Verification Similarity')),
                ('correction_type', models.CharField(max_length=255, verbose_name='Correction Type')),
                ('outlier_test_type', models.CharField(max_length=25, verbose_name='Outlier Test Type')),
                ('status', models.CharField(max_length=25, verbose_name='Status')),
                ('sample_name', models.CharField(max_length=255, verbose_name='Sample Name')),
                ('quality', models.CharField(max_length=255, verbose_name='Quality')),
                ('lot_no', models.CharField(max_length=255, verbose_name='Lot No.')),
                ('report_no', models.CharField(max_length=255, verbose_name='Report No.')),
                ('sample_id', models.CharField(max_length=255, verbose_name='Sample Id.')),
                ('fc', models.CharField(max_length=255, verbose_name='FC')),
                ('cc', models.CharField(max_length=255, verbose_name='CC')),
                ('diam', models.CharField(max_length=255, verbose_name='Diam')),
                ('stamp', models.CharField(max_length=255, verbose_name='Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=25)),
                ('analysis_name', models.CharField(max_length=25)),
                ('value_text', models.CharField(max_length=50, verbose_name='Value (Text)')),
                ('value', models.FloatField(help_text='Use only number for calculation purpose', verbose_name='Value')),
                ('analysis_report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.analysisreport')),
            ],
            options={
                'unique_together': {('analysis_report_id', 'analysis_type')},
            },
        ),
    ]
