# Generated by Django 4.0.2 on 2022-04-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_type_analysisreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='analysis_report_name',
            field=models.CharField(default='test', max_length=255, verbose_name='Analysis Report name'),
            preserve_default=False,
        ),
    ]
