# Generated by Django 4.0.2 on 2022-04-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reports', '0004_analysisreport_analysis_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='lot_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Lot No.'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='measure_date_time',
            field=models.CharField(max_length=255, verbose_name='Measure Date Time'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='recalculation_date_time',
            field=models.CharField(max_length=255, verbose_name='Recalculation Date Time'),
        ),
    ]
