# Generated by Django 4.0.2 on 2022-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_analysisreport_lot_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreportline',
            name='analysis_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
