# Generated by Django 4.0.2 on 2022-04-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_analysisreportline_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreportline',
            name='greater_than',
            field=models.BooleanField(default=False, verbose_name='Greater than'),
        ),
        migrations.AddField(
            model_name='analysisreportline',
            name='lower_than',
            field=models.BooleanField(default=False, verbose_name='Lower than'),
        ),
    ]
