# Generated by Django 4.0.4 on 2022-05-21 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_analysisreportline_greater_than_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['-pk', '-upload_date']},
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Upload Date'),
            preserve_default=False,
        ),
    ]
