# Generated by Django 4.0.4 on 2022-05-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_analysisreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreportline',
            name='analysis_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='reports.analysisreport'),
        ),
    ]
