# Generated by Django 4.0.2 on 2022-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('lot_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Lot NO.')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product name')),
                ('product_code', models.CharField(max_length=255, verbose_name='Product code')),
                ('part_code', models.CharField(max_length=255, verbose_name='Part code')),
            ],
        ),
    ]
