# Generated by Django 4.0.2 on 2022-02-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=255, unique=True, verbose_name='Spec name')),
                ('remark', models.TextField(verbose_name='Remark')),
            ],
        ),
        migrations.CreateModel(
            name='StandardSpecLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('value_text', models.CharField(max_length=25, verbose_name='Value (Text)')),
                ('value', models.CharField(help_text='Use only number for calculation purpose', max_length=25, verbose_name='Value')),
                ('standard_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standardspec.standardspec')),
            ],
        ),
    ]
