# Generated by Django 4.0.4 on 2022-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardspec', '0002_standardspec_remark2_standardspec_remark3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardspec',
            name='spec_name',
            field=models.CharField(max_length=255, verbose_name='Spec name'),
        ),
    ]
