# Generated by Django 4.0.4 on 2022-05-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardspec', '0003_alter_standardspec_spec_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardspec',
            name='spec_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Spec name'),
        ),
    ]
