# Generated by Django 4.0.4 on 2022-05-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardspec', '0004_alter_standardspec_spec_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardspecline',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='name'),
        ),
    ]
