# Generated by Django 4.0.4 on 2022-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardspec', '0006_alter_standardspecline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardspecline',
            name='standard_name',
            field=models.CharField(default=21, max_length=255, unique=True, verbose_name='Standard name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardspecline',
            name='value',
            field=models.CharField(blank=True, help_text='Use only number for calculation purpose', max_length=25, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='standardspecline',
            name='value_text',
            field=models.CharField(blank=True, max_length=25, verbose_name='Value (Text)'),
        ),
        migrations.AlterUniqueTogether(
            name='standardspecline',
            unique_together={('standard_spec_id', 'name')},
        ),
    ]
